import { NextPage } from "next";
import Link from 'next/link'
import Head from "next/head";
import Layout from "../../components/Layouts";

const PrimerPost: NextPage = () => {
    return (<Layout>
        <Head>
            <title>Mi primer post</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>Primer Post</h1>
        <h2 className='title'>
            Regresar{' '}
            <Link href="/" >
                Pagina principal
            </Link>

        </h2>
    </Layout>)
}

export default PrimerPost