from turtle import Turtle


class SafeZone(Turtle):
    def __init__(self):
        super().__init__()
        self.penup()
        self.goto(410, -270)
        self.color("green")
        self.pensize(60)
        self.pendown()
        self.seth(180)
        self.fd(820)
        self.hideturtle()
        self.penup()
        self.seth(90)
        self.fd(90)
        self.seth(0)
        self.pensize(40)
        self.pendown()
        self.fd(820)
        self.seth(90)
        self.penup()
        self.fd(100)
        self.seth(180)
        self.pensize(40)
        self.pendown()
        self.fd(820)
        self.seth(90)
        self.penup()
        self.fd(50)
        self.seth(0)
        self.pensize(20)
        self.pendown()
        self.fd(820)
        self.seth(90)
        self.penup()
        self.fd(50)
        self.seth(180)
        self.pensize(40)
        self.pendown()
        self.fd(820)
        self.seth(90)
        self.penup()
        self.fd(140)
        self.seth(0)
        self.pensize(40)
        self.pendown()
        self.fd(820)
        self.seth(90)
        self.penup()
        self.fd(110)
        self.seth(180)
        self.pensize(60)
        self.pendown()
        self.fd(820)
